name: Lint & Test & Build & Release

on:
  push:
    tags:
      - "v*"
    branches:
      - "!*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lint & Test & Build & Release
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Checkout
        uses: actions/checkout@v2.3.5
        with:
          fetch-depth: 0

      - name: Test
        run: |
          make test

      - name: Install GoReleaser
        run: |
          make install-tools

      - name: Run GoReleaser
        if: success()
        run: |
          make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
